# Numpy

Written in C, brings array capabilities in Python.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3.5,"Hello"]
a

[1, 2, 3.5, 'Hello']

In [7]:
# All data types will be converted to strings in this case
np.array(a)

array(['1', '2', '3.5', 'Hello'], dtype='<U32')

In [10]:
# All data types will be converted to float in this case
a = [1,2,3.5]
np.array(a)

array([1. , 2. , 3.5])

In [13]:
# 2D Array
l = [[1,2,3],[4,5,6], [7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Scalar: A single numerical value.
# Vector: A one-dimensional collection of numerical values.
# Matrix: A two-dimensional rectangular arrangement of numerical values.
# Tensor: A multi-dimensional array of numerical values.

In [19]:
# Generate an Array
# Takes start, end, step
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

#### Zeros and Ones

In [22]:
# Array of Zeros
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [24]:
# 2D Array of Zeros
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### Linear Spacing

In [27]:
# Takes start, stop and num of elements
# Returns num of elements, evenly spaced between start and stop
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [29]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### Random Number Generation

In [34]:
# Generate array of random numbers - normalized (i.e. all values between 0 and 1)
np.random.rand(10)

array([0.26647869, 0.04892528, 0.42630897, 0.24205033, 0.03067398,
       0.30403152, 0.11418387, 0.88813104, 0.62713547, 0.43736391])

In [35]:
# Generate array of random numbers - standardized (i.e. all values between -3 and 3)
np.random.randn(10)

array([ 0.63351506,  0.75931919,  1.73863047,  0.50180849,  1.47938174,
       -1.25724137, -1.14476572,  1.91140156, -1.28063911, -1.37090996])

In [37]:
# Generate a random number from 0 to specified number
np.random.randint(6)

5

In [38]:
# randint(start, end, n) :- Generates 'n' random numbers between start and end
np.random.randint(10,20,20)

array([10, 12, 19, 10, 14, 15, 15, 15, 16, 16, 12, 19, 15, 14, 12, 13, 16,
       13, 17, 12], dtype=int32)

#### Array Attributes

In [47]:
# Attributes are variables defined in a class, not called just printed

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
# Returns the row and columns
arr.shape

(3, 3)

In [51]:
# Returns the no of elements
arr.size

9

In [52]:
# Returns the data ttype
arr.dtype

dtype('int64')

#### Array Methods

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr.min()

np.int64(1)

In [55]:
arr.max()

np.int64(9)

In [57]:
# Inbuilt Function
arr.sum()

np.int64(45)

In [60]:
# np also provides a sum function, that takes in the array and axis
# axis = 0 -> Column wise
np.sum(arr, axis=0)

array([12, 15, 18])

In [61]:
# axis = 1 -> Row wise
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [62]:
arr.mean()

np.float64(5.0)

In [63]:
arr.std()

np.float64(2.581988897471611)

In [64]:
# Returns index of max element
arr.argmax()

np.int64(8)

In [65]:
# Returns index of min eNotImplemented
arr.argmin()

np.int64(0)

#### Reshaping and Resizing

In [66]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [68]:
# If you are reshaping, you need to keep the number of elements sNameError
arr = arr.reshape(6,5)

#### Numpy Indexing and Slicing

In [70]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [74]:
# Define the start point and end point (non-inclusive)
arr[1:5]

array([12, 13, 14, 15])

In [75]:
# Start value is 0 default and end is the size - 1 (last index)
arr[:5]

array([11, 12, 13, 14, 15])

In [76]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [77]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [78]:
# The third element it takes is step
arr[3::2]

array([14, 16, 18, 20])

In [81]:
arr = np.arange(1,31).reshape((6,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [82]:
arr[0,0]

np.int64(1)

In [83]:
arr[5,4]

np.int64(30)

In [85]:
# If we need specific part of this matrix
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [87]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [88]:
arr[:,2:3]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]])

In [89]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

#### Boolean Indexing

In [90]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [92]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [93]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

#### Array Operations

In [99]:
# Size should be same for both arrays while performing array operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [100]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [101]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [102]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [103]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [104]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [105]:
a2 // a1

array([6, 3, 2, 2, 2])

#### Broadcasting

In [106]:
l = [10,20,30,40,50]
arr = np.array(l)

In [107]:
# If we want to add 10 to each element, we won't be able to do so like l + 10a
# We can instead
arr + 10

array([20, 30, 40, 50, 60])

In [109]:
l # l will still stay the same

[10, 20, 30, 40, 50]

In [110]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [111]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

#### Deep vs Shallow Copy

In [123]:
# A shallow copy creates a new outer object, but nested objects are still shared.
import copy

original = [[1, 2], [3, 4]]
shallow = copy.copy(original)

shallow[0][0] = 99

print(original)  # [[99, 2], [3, 4]]
print(shallow)   # [[99, 2], [3, 4]]

[[99, 2], [3, 4]]
[[99, 2], [3, 4]]


In [125]:
# A deep copy creates a new outer object and recursively copies nested objects.
import copy

original = [[1, 2], [3, 4]]
deep = copy.deepcopy(original)

deep[0][0] = 99

print(original)  # [[1, 2], [3, 4]]
print(deep)      # [[99, 2], [3, 4]]

[[1, 2], [3, 4]]
[[99, 2], [3, 4]]


In [127]:
# Shallow Copy in Numpy
import numpy as np

a = np.array([1, 2, 3, 4])
b = a.view()

b[0] = 99

print(a)  # [99  2  3  4]
print(b)  # [99  2  3  4]

[99  2  3  4]
[99  2  3  4]


In [128]:
# Deep Copy in Numpy
import numpy as np

a = np.array([1, 2, 3, 4])
b = a.copy()

b[0] = 99

print(a)  # [1 2 3 4]
print(b)  # [99  2  3  4]

[1 2 3 4]
[99  2  3  4]


#### Matrix Operations

In [129]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [132]:
A

array([[1, 2],
       [3, 4]])

In [133]:
B

array([[5, 6],
       [7, 8]])

In [134]:
# Matrix Multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [135]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [136]:
# Transpose Matrix
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [137]:
A.T

array([[1, 3],
       [2, 4]])

In [138]:
# Stacking of Arrays
# In NumPy, stacking combines multiple arrays into a single array. 

In [140]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [141]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [142]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
# Splitting Array
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [147]:
# If you try to split into something that does not result in an equal disision, it will throw an error
np.hsplit(c, 2) 

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [149]:
np.vsplit(c, 4) # Still split in 2D Matrix

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]